name: test

on: [push, pull_request]

# TODO: Introduce caching https://github.com/actions/cache/blob/master/examples.md#rust---cargo
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1

    - name: Rust Version Info
      run: rustc --version && cargo --version

    - name: Run tests
      run: RUSTFLAGS="-D warnings" cargo test --workspace

    - name: Run tests with no defaults
      run: RUSTFLAGS="-D warnings" cargo test --workspace --no-default-features
